# Generated by Django 3.2 on 2021-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Email address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
