# Generated by Django 3.2 on 2021-04-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.CharField(max_length=100)),
                ('bright_vs_dark', models.IntegerField()),
                ('full_vs_hollow', models.IntegerField()),
                ('smooth_vs_rough', models.IntegerField()),
                ('warm_vs_metallic', models.IntegerField()),
                ('clear_vs_muddy', models.IntegerField()),
                ('thin_vs_thick', models.IntegerField()),
                ('pure_vs_noisy', models.IntegerField()),
                ('rich_vs_sparse', models.IntegerField()),
                ('soft_vs_hard', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
