# Generated by Django 3.2 on 2021-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='was_played',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
